### ISSUE TITLE
Problem when building the Dockerfile for cassandra

### ISSUE THREAD

**Issue by khaferkamp** [thelastpickle/docker-cassandra-bootstrap#1]
Hi!

Many thanks for the great compose file. Looks awesome but I struggle to get the setup running.

When I hit "docker-compose build" I receive an error with installing collectd that I do not get fixed.
Would be awesome if you or someone else could guide me to the right direction how to solve this problem.

Trace:
The following packages have unmet dependencies:
 collectd : Depends: librrd4 (>= 1.3.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'cassandra' failed to build: The command '/bin/sh -c set -x     && echo "deb http://pkg.ci.collectd.org/deb jessie collectd-5.7"         > /etc/apt/sources.list.d/pkg.ci.collectd.org.list     && gpg --keyserver pgp.mit.edu --recv-keys 3994D24FB8543576         && gpg --export -a 3994D24FB8543576 | apt-key add -     && apt-get update         && apt-get install -y --no-install-recommends             collectd             collectd-utils             libprotobuf-c-dev             libmicrohttpd-dev         && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by joaquincasares** [comment]
Hello @khaferkamp , glad you're liking the compose file so far! :)

Thanks for spotting and filing this issue.

I've pushed this commit (5755f9d5310da41e3381c124f61c5d644b03cb03) to workaround the current issue.

It seems as though the newer version of collectd is broken and was trying to use a library that does not exist in the Ubuntu repos. I've forced the version of collectd to be an older version so the build continues as expected. I've tested this locally to confirm that `docker-compose build` now works for me.

Do please test this on your side and let me know if you spot any other issues or have any other questions on the project.

Thanks again and enjoy the project! :)
