### ISSUE TITLE
Documented Steps fail when trying to start Cassandra

### ISSUE THREAD

**Issue by CaryBourgeois** [thelastpickle/docker-cassandra-bootstrap#2]
Following the steps in the README, when I get to the point where I run `docker-compose up cassandra` the container create fails with the message below.

Looks like collectd is looking for a file other than the `/var/log/collectd.lig` maybe?

docker-cassandra-bootstrap_cassandra_1|Created new plugin context.
docker-cassandra-bootstrap_cassandra_1|[2018-09-21 20:29:01] plugin_load: plugin "logfile" successfully loaded.
docker-cassandra-bootstrap_cassandra_1|[2018-09-21 20:29:01] type = logfile, key = LogLevel, value = debug
docker-cassandra-bootstrap_cassandra_1|[2018-09-21 20:29:01] type = logfile, key = File, value = /var/log/collectd.log
docker-cassandra-bootstrap_cassandra_1|ERROR: lt_dlopen ("/usr/lib/collectd/rrdtool.so") failed: file not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
docker-cassandra-bootstrap_cassandra_1|ERROR: lt_dlopen ("/usr/lib/collectd/write_prometheus.so") failed: file not found. The most common cause for this problem is missing dependencies. Use ldd(1) to check the dependencies of the plugin / shared object.
docker-cassandra-bootstrap_cassandra_1|Error: Reading the config file failed!
docker-cassandra-bootstrap_cassandra_1|Starting statistics collection and monitoring daemon: collectd not starting, configuration error failed!
docker-cassandra-bootstrap_cassandra_1|Read the logs for details.

**Comment by joaquincasares** [comment]
Hey @CaryBourgeois ! Nice to see you! :) It looks like if the error is coming from these lines:

https://github.com/thelastpickle/docker-cassandra-bootstrap/blob/master/cassandra/Dockerfile#L63-L76

I'll give it a shot on Monday and see if perhaps we need to update the packages to use newer versions. What I'm seeing is that `rrdtool.so` and `write_prometheus.so` are not installed.

https://collectd.org/wiki/index.php/Plugin:RRDtool
https://collectd.org/wiki/index.php/Plugin:Write_Prometheus

**Comment by CaryBourgeois** [comment]
Thanks for highlighting the issue. I attempted to add those python libraries to the image and TBH it was a pretty heavy lift at the container level. It was going to leave way to much surface area in the image to simply add them in. Looking forward to seeing if you have a better solution.

Cary Bourgeois

**Comment by joaquincasares** [comment]
Hey Cary, try could you try master again please and let me know if it works?

You'll need to rebuild the images using `docker-compose build`. Let me know if you have any further issues!

**Comment by CaryBourgeois** [comment]
That worked. I had some issues with the mit pgp repo. that was fixed by changing the endpoint 

from: http://pgp.mit.edu
to: hkp://pgp.mit.edu:80

in the cassandra/Dockerfile line 68.

Thanks for looking into this.

**Comment by joaquincasares** [comment]
Sounds good! I've tested that change and it seemed to work a bit more reliably as well on my end. Thanks for the tip!

Sure thing, any time. :)
